---
title: "CodeBook.md"
author: "Polina Koroleva"
date: "24 01 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Modifications 

The dataset for the modifications is sourced at https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 

The script "run_analysis.R" provides the following modifications :
1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.


## Descriptions

The following labels were changed:

- Subject: the ID of the Subject
- Activity: the Name of the Activity performed by the subject when measurements were taken

## Variable names

The following variable names were changed due to make them readable:

* "f" - "frequencyDomain"
* "^t" - "timeDomain", 
* "Acc" -  "Accelerometer", 
* "Gyro" -  "Gyroscope",
* "Mag" -  "Magnitude", 
* "Freq" -  "Frequency",
* "BodyBody" - "Body", 
* "mean" - "Mean"
* "std" -  "Std",